eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http:localhost:8761/eureka}
logging:
  level:
    root: warn
server:
  port: ${SERVER_PORT}
spring:
  application:
    name: product-service
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_URI}/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
  devtools:
    livereload:
      port: ${LIVERELOAD_PORT:35730}
      enabled: true
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_BASE_URI}/realms/${REALM}
        opaquetoken:
          client-secret: ${CLIENT_SECRET}
          client-id: product-service
          introspection-uri: http://${KEYCLOAK_BASE_URI}/realms/${REALM}/protocol/openid-connect/token/introspect