CREATE TABLE comp_product
(
    id                    BIGINT       NOT NULL,
    title                 VARCHAR(255) NOT NULL,
    description           VARCHAR(255),
    condition             VARCHAR(255) NOT NULL,
    price                 INTEGER      NOT NULL,
    quantity              INTEGER      NOT NULL,
    cpu                   VARCHAR(255) NOT NULL,
    ram_capacity          INTEGER      NOT NULL,
    ram_type              VARCHAR(255) NOT NULL,
    gpu_type              VARCHAR(255) NOT NULL,
    gpu_model             VARCHAR(255),
    gpu_vram_capacity     INTEGER,
    gpu_vram_type         VARCHAR(255),
    storage_unit_type     VARCHAR(255),
    storage_unit_capacity INTEGER,
    os                    VARCHAR(255),
    good_for              VARCHAR(255) NOT NULL,
    CONSTRAINT pk_compproduct PRIMARY KEY (id)
);

CREATE TABLE default_product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    condition   VARCHAR(255)                            NOT NULL,
    price       INTEGER                                 NOT NULL,
    quantity    INTEGER                                 NOT NULL,
    CONSTRAINT pk_defaultproduct PRIMARY KEY (id)
);

CREATE TABLE laptop_product
(
    id                    BIGINT       NOT NULL,
    title                 VARCHAR(255) NOT NULL,
    description           VARCHAR(255),
    condition             VARCHAR(255) NOT NULL,
    price                 INTEGER      NOT NULL,
    quantity              INTEGER      NOT NULL,
    cpu                   VARCHAR(255) NOT NULL,
    ram_capacity          INTEGER      NOT NULL,
    ram_type              VARCHAR(255) NOT NULL,
    gpu_type              VARCHAR(255) NOT NULL,
    gpu_model             VARCHAR(255),
    gpu_vram_capacity     INTEGER,
    gpu_vram_type         VARCHAR(255),
    storage_unit_type     VARCHAR(255),
    storage_unit_capacity INTEGER,
    os                    VARCHAR(255),
    good_for              VARCHAR(255) NOT NULL,
    release_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    comes_with_charger    BOOLEAN      NOT NULL,
    screen_type           VARCHAR(255) NOT NULL,
    screen_resolution     VARCHAR(255) NOT NULL,
    has_backlit           BOOLEAN      NOT NULL,
    battery_health        INTEGER,
    model                 VARCHAR(255) NOT NULL,
    CONSTRAINT pk_laptopproduct PRIMARY KEY (id)
);

CREATE TABLE COMP_ID_GENERATOR
(
    COMP_ID_KEY VARCHAR(255) NOT NULL,
    COMP_ID_VALUE BIGINT NOT NULL,
    PRIMARY KEY (COMP_ID_KEY)
)
