CREATE TABLE cart
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_user_id BIGINT,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE product_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255),
    country    VARCHAR(255),
    city       VARCHAR(255),
    address    VARCHAR(255),
    apartment  VARCHAR(255),
    cart_id    BIGINT,
    CONSTRAINT pk_product_user PRIMARY KEY (id)
);

ALTER TABLE cart
    ADD CONSTRAINT uc_cart_product_user UNIQUE (product_user_id);

ALTER TABLE cart
    ADD CONSTRAINT FK_CART_ON_PRODUCT_USER FOREIGN KEY (product_user_id) REFERENCES product_user (id);

ALTER TABLE comp_product
    ADD COLUMN cart_id BIGINT;

ALTER TABLE comp_product
    ADD CONSTRAINT FK_COMPPRODUCT_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE default_product
    ADD COLUMN cart_id BIGINT;

ALTER TABLE default_product
    ADD CONSTRAINT FK_DEFAULTPRODUCT_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE laptop_product
    ADD COLUMN cart_id BIGINT;

ALTER TABLE laptop_product
    ADD CONSTRAINT FK_LAPTOP_PRODUCT_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE product_user
    ADD CONSTRAINT FK_PRODUCT_USER_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);